apiVersion: v1
kind: Service
metadata:
  name: managed-node1-service
spec:
  selector:
    app: managed-node1
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
